### ISSUE TITLE
L'utilisateur peut modifier son profil

### ISSUE THREAD

**Issue by lpavius** [lpavius/4Share-Application#1]
### Description du cas d'utilisation:
L'utilisateur (connecté) peut accéder à sa page de profil ou il peut lire ou modifier ses informations.

### Tâches:

- [x] Ajouter une page de profil

- [x] créer un formulaire désactivé

- [x] Ajouter le bouton modifier
