### ISSUE TITLE
un visiteur peut voir la page d'accueil

### ISSUE THREAD

**Issue by lpavius** [lpavius/4Share-Application#2]
### Description du cas d'utilisation:
Le visiteur peut voir sur la page d'accueil une liste par type de fichier, une barre de recherche désactivé et peut accéder au formulaire de connexion ou d'enregistrement.

### Tâches:

- [x] Ajouter une barre de nav #3

- [x] Ajouter une barre de recherche #4 

- [x] Ajouter un formulaire de connexion #5 

- [x] Ajouter un formulaire d'enregistrement #6 

- [x] Ajouter un footer #7
